services:
  db:
    image: mysql:8.0.32
    container_name: seibo_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: